# Generated by Django 3.0.5 on 2020-04-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pasta_salads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
    ]
